server:
  port: 7074

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/javaTahminDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



